import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import AirdropPopUp from "@/components/airdropPopUp";
import TrendingSection from "@/components/TrendingSection";
import CollectionHeroSection from "@/components/CollectionHeroSection";
import CollectionHeader from "@/components/CollectionHeader";

export default function Home() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Blur: NFT Marketplace for Pro Traders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale= 1" />
        <link rel="icon" type="" href="/favicon.ico" />
      </Head>
      <section>
        <section className={styles.main}>
        <Header/>
        <AirdropPopUp/>
        </section>
        <TrendingSection/>
      </section>
    </section>
  );
}
